{% set name = "defopt" %}
{% set version = "6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/defopt-{{ version }}.tar.gz
  sha256: a8fcd5560c845dceafd495d7dc97da355b1fdaa1881b5b83cf0fa4e9c7534285

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - docutils >=0.10
    - sphinxcontrib-napoleon >=0.7.0
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - typing_extensions >=3.7.4  # [py<38]
    - typing_inspect >=0.3.1  # [py<38]
    - docutils >=0.10
    - python >=3.5,<=3.8
    - sphinxcontrib-napoleon >=0.7.0
    - colorama  # [win32]

test:
  imports:
    - defopt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anntzer/defopt
  summary: Effortless argument parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nh13
