{% set name = "defopt" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/defopt-{{ version }}.tar.gz
  sha256: cfe6ecfb54b1368a5cc45d9d58fb3c125e4b4b789e08fd29b5722404b57e137d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools_scm
  run:
    - python >=3.5
    - typing_extensions >=3.7.4
    - typing_inspect >=0.3.1
    - docutils >=0.10
    - sphinxcontrib-napoleon >=0.7.0
    - colorama

test:
  imports:
    - defopt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/anntzer/defopt
  summary: Effortless argument parser
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nh13
